name: flatcn_ui
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  http: ^1.3.0
  json_annotation: ^4.9.0
  path: ^1.8.0
  yaml: ^3.1.3
dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.9.3
  lints: ^5.0.0
  test: ^1.24.0
