name: flutcn_ui
description: A UI component library for Flutter inspired by shadcn/ui, providing modular and customizable widgets.
version: 0.1.0
repository: https://github.com/OmarElhassaniAlaoui/flutcn_ui
environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  cli_spin: ^1.0.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  get_it: ^8.0.3
  http: ^1.3.0
  io: ^1.0.5
  json_annotation: ^4.9.0
  path: ^1.8.0
  prompts: ^2.0.0
  yaml: ^3.1.3
dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.9.3
  lints: ^5.0.0
  test: ^1.24.0
false_secrets:
  - /bin/**

executables:
  flutcn_ui: flutcn_ui
